### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by nemoo** [vmunier/scalajs-simple-canvas-game#4]
Sorry, just a usage question: 

How do I actally run the game? I start it with `sbt ~fastOptJ` and it builds successfully. But where can I see the result in the browser? Do I need to deploy it to a web server or is there something built in?

**Comment by vmunier** [comment]
Hi,
I have edited the README.md to describe how to run the application:
```
$ sbt
> fastOptJS
$ open index-dev.html
```

**Comment by nemoo** [comment]
Thanks! I thried to open http://localhost:8080/index-dev.html but that was obviously the wrong URL that I tried. Under which URL will index-dev.html be exposed?

**Comment by vmunier** [comment]
You need to open the `index-dev.html` file into your browser: Right click on the file -> open.
